import { ReelsMediaFeedResponseVideoVersionsItem } from './reels-media-feed-response-video-versions-item.model';
import { ReelsMediaFeedResponseImageVersions2 } from './reels-media-feed-response-image-versions-2.model';
import { ReelsMediaFeedResponseUser } from './reels-media-feed-response-user.model';
import { ReelsMediaFeedResponseReelMentionsItem } from './reels-media-feed-response-reel-mentions-item.model';
import { ReelsMediaFeedResponseStoryCtaItem } from './reels-media-feed-response-story-cta-item.model';
import { ReelsMediaFeedResponseStoryPollsItem } from './reels-media-feed-response-story-polls-item.model';
import { ReelsMediaFeedResponseStoryQuestionsItem } from './reels-media-feed-response-story-questions-item.model';
import { ReelsMediaFeedResponseStoryQuizsItem } from './reels-media-feed-response-story-quizs-item.model';
import { ReelsMediaFeedResponseStorySlidersItem } from './reels-media-feed-response-story-sliders-item.model';
import { ReelsMediaFeedResponseStoryCountdownsItem } from './reels-media-feed-response-story-countdowns-item.model';

export interface ReelsMediaFeedResponseItem {
  taken_at: number;
  pk: string;
  id: string;
  device_timestamp: string;
  media_type: number;
  code: string;
  client_cache_key: string;
  filter_type: number;
  image_versions2: ReelsMediaFeedResponseImageVersions2;
  original_width: number;
  original_height: number;
  caption_position: number;
  is_reel_media: boolean;
  is_dash_eligible: number;
  video_dash_manifest: string;
  video_codec: string;
  number_of_qualities: number;
  video_versions: ReelsMediaFeedResponseVideoVersionsItem[];
  has_audio: boolean;
  video_duration: number;
  user: ReelsMediaFeedResponseUser;
  caption_is_edited: boolean;
  photo_of_you: boolean;
  caption: null;
  can_viewer_save: boolean;
  organic_tracking_token: string;
  expiring_at: number;
  can_reshare: boolean;
  can_reply: boolean;
  reel_mentions?: ReelsMediaFeedResponseReelMentionsItem[];
  supports_reel_reactions: boolean;
  show_one_tap_fb_share_tooltip: boolean;
  has_shared_to_fb: number;
  ad_action?: string;
  link_text?: string;
  story_cta?: ReelsMediaFeedResponseStoryCtaItem[];
  imported_taken_at?: number;
  story_polls?: ReelsMediaFeedResponseStoryPollsItem[];
  story_questions?: ReelsMediaFeedResponseStoryQuestionsItem[];
  story_quizs?: ReelsMediaFeedResponseStoryQuizsItem[];
  story_sliders?: ReelsMediaFeedResponseStorySlidersItem[];
  story_countdowns?: ReelsMediaFeedResponseStoryCountdownsItem[];
}
